# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Define log levels
logger:
  default: warning
  logs:
    homeassistant.core: warning
    homeassistant.components.mqtt: warning
    custom_components.hacs: info
    custom_components.rki_covid.sensor: debug

tankerkoenig:
 api_key: !secret tanker_api_key
 fuel_types:
    - "diesel"
 latitude: !secret tanker_latitude
 longitude: !secret tanker_longitude
 radius: 1
 show_on_map: true

# https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
  ### The following installs all package files
  packages: !include_dir_named packages

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml

# define config files for automations
automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml

script: !include scripts.yaml
scene: !include scenes.yaml

# temperatur failing sensor (at least 3 degrees in 30 minutes)
binary_sensor:
  - platform: trend
    sensors:
      childrens_room_cooling_down:
        entity_id: sensor.0x00158d0004aac23c_temperature
        sample_duration: 7200
        max_samples: 120
        min_gradient: -0.001388
        device_class: cold
      bedroom_cooling_down:
        entity_id: sensor.0x00158d00053dfbb6_temperature
        sample_duration: 7200
        max_samples: 120
        min_gradient: -0.001388
        device_class: cold
